In [93]:
import numpy as np

In [5]:
np.arange(15)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [6]:
np.arange(15).reshape(3,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [7]:
a=np.arange(15).reshape(3,5)

In [14]:
print(f"dim--{a.ndim} dtype--{a.dtype} itemsize --{a.itemsize} type--{type(a)}")

dim--2 dtype--int64 itemsize --8 type--<class 'numpy.ndarray'>


**array creation**

In [18]:
b = np.array([1,2,3,5.1])

In [20]:
b , b.dtype

(array([1. , 2. , 3. , 5.1]), dtype('float64'))

In [22]:
c = np.array([(1,2,3),(10,20,30)])

In [23]:
c

array([[ 1,  2,  3],
       [10, 20, 30]])

In [29]:
np.zeros((3,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [30]:
np.ones((3,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [3]:
np.empty((3,5))

array([[6.95262084e-310, 6.95266975e-310, 6.95262085e-310,
        0.00000000e+000, 0.00000000e+000],
       [0.00000000e+000, 0.00000000e+000, 0.00000000e+000,
        0.00000000e+000, 0.00000000e+000],
       [0.00000000e+000, 0.00000000e+000, 0.00000000e+000,
        0.00000000e+000, 0.00000000e+000]])

In [7]:
np.arange(10,30,5)

array([10, 15, 20, 25])

np.linspace getting some numbers between x and y

In [ ]:
np.linspace(0,1,9) 

array([0.        , 0.02040816, 0.04081633, 0.06122449, 0.08163265,
       0.10204082, 0.12244898, 0.14285714, 0.16326531, 0.18367347,
       0.20408163, 0.2244898 , 0.24489796, 0.26530612, 0.28571429,
       0.30612245, 0.32653061, 0.34693878, 0.36734694, 0.3877551 ,
       0.40816327, 0.42857143, 0.44897959, 0.46938776, 0.48979592,
       0.51020408, 0.53061224, 0.55102041, 0.57142857, 0.59183673,
       0.6122449 , 0.63265306, 0.65306122, 0.67346939, 0.69387755,
       0.71428571, 0.73469388, 0.75510204, 0.7755102 , 0.79591837,
       0.81632653, 0.83673469, 0.85714286, 0.87755102, 0.89795918,
       0.91836735, 0.93877551, 0.95918367, 0.97959184, 1.        ])

In [14]:
from numpy import pi

In [15]:
x = np.linspace(0,2*pi,10)

In [16]:
x

array([0.        , 0.6981317 , 1.3962634 , 2.0943951 , 2.7925268 ,
       3.4906585 , 4.1887902 , 4.88692191, 5.58505361, 6.28318531])

In [18]:
np.sin(x)

array([ 0.00000000e+00,  6.42787610e-01,  9.84807753e-01,  8.66025404e-01,
        3.42020143e-01, -3.42020143e-01, -8.66025404e-01, -9.84807753e-01,
       -6.42787610e-01, -2.44929360e-16])

### Basic Operations 

In [26]:
a = np.array([10,20,30])
b = np.arange(3)

In [27]:
a+b

array([10, 21, 32])

In [28]:
b**2

array([0, 1, 4])

In [29]:
10 * np.sin(a)

array([-5.44021111,  9.12945251, -9.88031624])

In [31]:
a < 15

array([ True, False, False])

In [ ]:
x1 = np.array([[1,0],
               [0,1]])
x2 = np.array([[2,5],
               [4,5]])

In [34]:
x1 * x2

array([[2, 0],
       [0, 5]])

In [35]:
x1 @ x2

array([[2, 5],
       [4, 5]])

In [36]:
np.dot(x1,x2)

array([[2, 5],
       [4, 5]])

In [56]:
rg = np.random.default_rng(1)

In [20]:
a = np.ones((2,3),dtype=int)

In [17]:
b = rg.random((2,3))

In [23]:
a *= 3

In [24]:
b += a

In [25]:
b

array([[3.32973172, 3.7884287 , 3.30319483],
       [3.45349789, 3.1340417 , 3.40311299]])

In [29]:
b.sum(),b.min(),b.max()

(np.float64(20.412007822394088),
 np.float64(3.1340416972471647),
 np.float64(3.788428703428404))

In [32]:
b = np.arange(12).reshape((3,4))

In [33]:
b

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [41]:
b.sum(axis=0),b.min(axis=1),b.cumsum(axis=1)

(array([12, 15, 18, 21]),
 array([0, 4, 8]),
 array([[ 0,  1,  3,  6],
        [ 4,  9, 15, 22],
        [ 8, 17, 27, 38]]))

## Universal Functions

In [50]:
B = np.arange(15)

In [55]:
np.exp(B),np.sqrt(B),np.absolute(B),np.sum(B)

(array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
        5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
        2.98095799e+03, 8.10308393e+03, 2.20264658e+04, 5.98741417e+04,
        1.62754791e+05, 4.42413392e+05, 1.20260428e+06]),
 array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
        2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ,
        3.16227766, 3.31662479, 3.46410162, 3.60555128, 3.74165739]),
 array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14]),
 np.int64(105))

## Indexing, slicing and iterating

In [12]:
a = np.arange(10)**3

In [4]:
a

array([  0,   1,   8,  27,  64, 125, 216, 343, 512, 729])

In [9]:
a[:5:2] = 100

In [10]:
a

array([100,   1, 100,  27, 100, 125, 216, 343, 512, 729])

In [13]:
for i in a:
    print(i**(1/3))

0.0
1.0
2.0
3.0
3.9999999999999996
4.999999999999999
5.999999999999999
6.999999999999999
7.999999999999999
8.999999999999998


In [39]:
def f(x,y):
    return 10*x + y

In [40]:
b = np.fromfunction(f,(4,5),dtype=int)

In [41]:
b

array([[ 0,  1,  2,  3,  4],
       [10, 11, 12, 13, 14],
       [20, 21, 22, 23, 24],
       [30, 31, 32, 33, 34]])

In [46]:
b[:-1]

array([[ 0,  1,  2,  3,  4],
       [10, 11, 12, 13, 14],
       [20, 21, 22, 23, 24]])

In [54]:
td = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])

In [55]:
td.shape

(2, 2, 3)

## shape manipulation

In [65]:
rg.random((3,4),dtype=float).T.reshape((6,2)).ravel()

array([0.89471586, 0.67345989, 0.66035538, 0.42271691, 0.91908862,
       0.24555227, 0.58950206, 0.82682533, 0.768517  , 0.02449068,
       0.88552027, 0.21167474])

In [69]:
a = np.floor(10*rg.random((3,4),dtype=float))

In [73]:
a.resize(2,6)

resize modifies the array itself whereas reshape does return a modifed array

## Stacking

In [85]:
a = np.floor(10*rg.random((2,2),dtype=float))
b = np.floor(10*rg.random((2,2),dtype=float))

In [86]:
a , b

(array([[0., 1.],
        [6., 5.]]),
 array([[1., 9.],
        [1., 5.]]))

In [88]:
np.vstack((a,b)),np.hstack((a,b))

(array([[0., 1.],
        [6., 5.],
        [1., 9.],
        [1., 5.]]),
 array([[0., 1., 1., 9.],
        [6., 5., 1., 5.]]))

In [94]:
from numpy import newaxis

In [95]:
np.column_stack((a,b))

array([[0., 1., 1., 9.],
       [6., 5., 1., 5.]])

In [96]:
a[:newaxis]

array([[0., 1.],
       [6., 5.]])

In [105]:
np.argmax(a),np.min(a),a.argmin(),a.max(),np.sort(a)

(np.int64(3),
 np.float64(0.0),
 np.int64(0),
 np.float64(6.0),
 array([[0., 1.],
        [5., 6.]]))

Splitting Arrays into multiple samll ones